### ISSUE TITLE
RAM doesn't appear in OpenRGB

### ISSUE THREAD

**Issue by namannarula** [ShadyNawara/macUSPCIO#1]
Hello, First of all, thank you so much for this kext. I finally got my Motherboard lighting to work!

The problem is that my RAM doesn't seem to appear in OpenRGB. I have 4 Sticks of XPG D60G, and they are just puking rainbows. 

Should I be doing something different for it to appear on the software? You've mentioned info.plist, but I'm not sure if I should be changing something over there. 

Please let me know about this; thanks.

**Comment by ShadyNawara** [comment]
Are you able to run windows or linux and send the openrgb logs from there

**Comment by namannarula** [comment]
> Are you able to run windows or linux and send the openrgb logs from there

I don't have any other OS Installed as of now, let me install windows on a different drive & get back to you.

**Comment by namannarula** [comment]
Hi, sorry it took me so long to get back. I've just managed to dual-boot my system with windows, and apparently, the RAM doesn't show up over there on OpenRGB either. So maybe it's not compatible with OpenRGB?
Not sure what to do next.

**Comment by ShadyNawara** [comment]
No worries, you should create a device request issue on the openrgb gitlab page

**Comment by dmikhalsky** [comment]
I have the same issue, except my RAM is detected by OpenRGB in Windows (but not on Hackintosh)
Here is the log from windows: 
```
[Info:] ------------------------------------------------------
[Info:] |             Detecting I2C interfaces               |
[Info:] ------------------------------------------------------
[Info:] Loading plugins
[Info:] Registering I2C interface: Intel(R) SMBus - A3A3 Device 8086:A3A3 Subsystem: 1043:8694
[Info:] Registering I2C interface: Nuvoton NCT6798D SMBus at B00 Device 0000:0000 Subsystem: 0000:0000
```
In "listed devices" I have Corsair Vengeance Pro (my modules) at address 0x5A and 0x58  

The same modules are not detected by OpenRGB in MacOS

**Comment by namannarula** [comment]
If you've installed the macUSPCIO kext already, can you try installing the OpenRGB Pipeline version? [Here's the link](https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/artifacts/master/download?job=MacOS%20Intel) for macOS (intel).

**Comment by ShadyNawara** [comment]
if the pipeline version doesnt work try this MR: [https://gitlab.com/CalcProgrammer1/OpenRGB/-/merge_requests/1242](https://gitlab.com/CalcProgrammer1/OpenRGB/-/merge_requests/1242)

**Comment by dmikhalsky** [comment]
The pipeline version solved the issue. Thanks A LOT, man!

**Comment by namannarula** [comment]
glad I could help!

**Comment by namannarula** [comment]
Hey @ShadyNawara!

This might be a bit out of the blue, but I just wanted to say thank you for building macUSPCIO.

I reinstalled macOS this week and realised this solved a problem I thought I’d just have to live with. 

thank you for doing this for the community! <3
